name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Create ZIP with correct structure
      run: |
        cd custom_components/zencontrol
        zip -r zencontrol.zip ./

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: zencontrol.zip
        generate_release_notes: true
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}