name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Create ZIP
      run: |
        cd custom_components
        zip -r ../zencontrol.zip zencontrol/*
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: zencontrol.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}