name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Create ZIP with correct structure
      run: |
        zip -r zencontrol.zip custom_components/zencontrol/*
        
    - name: Verify ZIP structure
      run: |
        unzip -l zencontrol.zip
        echo "Top-level contents:"
        unzip -l zencontrol.zip | grep -v '/.*/' | head -20
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: zencontrol.zip
        generate_release_notes: true
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}